feat: for visitors page
SlovakNationalGallery/floatingarboretum.sng.sk pull request #19
Opened 2024-03-19 14:33 UTC by FrantisekMichalSebestyen

2024-03-19 22:42 UTC, igor-kamil reviewed
looks very nice both on desktop and mobile. 
we need to include translations before releasing + fix the spacing between sections. 
almost there.

2024-03-19 22:42 UTC, igor-kamil commented on resources/js/ForVisitors.vue
> +            <section class="mb-4">
there should be bigger space under the section on desktop 
<img width="872" alt="Screenshot 2024-03-19 at 23 38 30" src="https://github.com/SlovakNationalGallery/floatingarboretum.sng.sk/assets/2682941/57cb3945-b037-4f54-8dfe-b2cbf71b67af">

in design:

<img width="743" alt="Screenshot 2024-03-19 at 23 40 15" src="https://github.com/SlovakNationalGallery/floatingarboretum.sng.sk/assets/2682941/f7dfcb10-2840-4899-8038-bab443b3ea67">

2024-03-20 13:09 UTC, FrantisekMichalSebestyen commented
Ja by som texty pripomienkoval: 3 rôzne formáty času v angličtine.
`Časy performancií počas preview`. Sa mi nezdá, ale tak hodím to tam.

2024-03-21 12:26 UTC, igor-kamil requested changes

2024-03-21 12:26 UTC, igor-kamil commented on resources/js/ForVisitors.vue
> +                    <span class="font-display text-2xl">{{ $t("19.4") }}</span>
```suggestion
                    <span class="font-display text-2xl">{{ $t("19.4.") }}</span>
```

2024-03-21 12:26 UTC, igor-kamil commented on resources/js/ForVisitors.vue
> +                    <span class="font-display text-2xl">{{ $t("17.4") }}</span>
```suggestion
                    <span class="font-display text-2xl">{{ $t("17.4.") }}</span>
```

2024-03-21 12:26 UTC, igor-kamil commented on resources/js/ForVisitors.vue
> +                    <span class="font-display text-2xl">{{ $t("18.4") }}</span>
```suggestion
                    <span class="font-display text-2xl">{{ $t("18.4.") }}</span>
```

2024-03-21 12:26 UTC, igor-kamil commented on resources/js/ForVisitors.vue
> +                    <span class="font-display text-2xl">{{ $t("18.4") }}</span>
```suggestion
                    <span class="font-display text-2xl">{{ $t("18.4.") }}</span>
```

2024-03-21 16:26 UTC, merged